 const itemDefinitions = {
    "copper_coin": new ItemTemplate("copper_coin", "Copper Coin", 1, 10000, ["Money"], {description:"A copper coin"}),
    "silver_coin": new ItemTemplate("silver_coin", "Silver Coin", 5, 10000, ["Money"], {description:"A silver coin"}),
    "gold_coin": new ItemTemplate("gold_coin", "Gold Coin", 10, 10000, ["Money"], {description:"A gold coin"}),
    "two_dollar": new ItemTemplate("two_dollar", "Two Dollar Bill", 100, 10000, ["Money", "Trinket", "Weird", "Ultra Rare"], {description:"A relic of a bygone era, given value again"}),
    //Gems
    "ruby": new ItemTemplate("ruby", "Ruby", 100, 100, ["Gem"], {description:"Shiny red gem", craftable:true, becomes:"cut_ruby", craftAmount:2}),
    "emerald": new ItemTemplate("emerald", "Emerald", 100, 100, ["Gem"], {description:"Shiny green gem", craftable:true, becomes:"cut_emerald", craftAmount:2}),
    "sapphire": new ItemTemplate("sapphire", "Sapphire", 100, 100, ["Gem"], {description:"Shiny blue gem", craftable:true, becomes:"cut_sapphire", craftAmount:2}),
    "amethyst": new ItemTemplate("amethyst", "Amethyst", 75, 100, ["Gem"], {description:"Shiny purple gem", craftable:true, becomes:"cut_amethyst", craftAmount:2}),
    "diamond": new ItemTemplate("diamond", "Diamond", 500, 100, ["Gem"], {description:"Shiny white gem", craftable:true, becomes:"cut_diamond", craftAmount:2}),
    "topaz": new ItemTemplate("topaz", "Topaz", 75, 100, ["Gem"], {description:"Shiny yellow gem", craftable:true, becomes:"cut_topaz", craftAmount:2}),
    "amber": new ItemTemplate("amber", "Amber", 50, 100, ["Gem"], {description:"Hardened golden orange sap", craftable:true, becomes:"cut_amber", craftAmount:2}),
    "cut_ruby": new ItemTemplate("cut_ruby", "Ruby", 75, 100, ["Gem", "Jewelery", "Crafting"], {description:"A cut shiny red gem"}),
    "cut_emerald": new ItemTemplate("cut_emerald", "Emerald", 60, 100, ["Gem", "Jewelery", "Crafting"], {description:"A cut shiny green gem"}),
    "cut_sapphire": new ItemTemplate("cut_sapphire", "Sapphire", 60, 100, ["Gem", "Jewelery", "Crafting"], {description:"A cut shiny blue gem"}),
    "cut_amethyst": new ItemTemplate("cut_amethyst", "Amethyst", 40, 100, ["Gem", "Jewelery", "Crafting"], {description:"A cut shiny purple gem"}),
    "cut_diamond": new ItemTemplate("cut_diamond", "Diamond", 275, 100, ["Gem", "Jewelery", "Crafting"], {description:"A cut shiny white gem"}),
    "cut_topaz": new ItemTemplate("cut_topaz", "Topaz", 40, 100, ["Gem", "Jewelery", "Crafting"], {description:"A cut shiny yellow gem"}),
    "cut_amber": new ItemTemplate("cut_amber", "Amber", 30, 100, ["Gem", "Jewelery", "Crafting"], {description:"A cut piece of hardened golden orange sap"}),
    "pearl": new ItemTemplate("pearl", "Pearl", 50, 100, ["Gem"], {description:"A proper pearl"}),
    "rose_pearl": new ItemTemplate("rose_pearl", "Rose Pearl", 100, 100, ["Gem"], {description:"A rare rose pearl"}),
    //Ore / Stone
    "copper_nugget": new ItemTemplate("copper_nugget", "Copper Nugget", 10, 100, ["Ore", "Metal"], {description:"A nugget of copper"}),
    "silver_nugget": new ItemTemplate("silver_nugget", "Silver Nugget", 30, 100, ["Ore", "Metal"], {description:"A nugget of silver"}),
    "iron_nugget": new ItemTemplate("iron_nugget", "Iron Nugget", 20, 100, ["Ore", "Metal"], {description:"A nugget of iron"}),
    "gold_nugget": new ItemTemplate("gold_nugget", "Gold Nugget", 50, 100, ["Ore", "Metal"], {description:"A nugget of gold"}),
    "platinum_nugget": new ItemTemplate("platinum_nugget", "Platinum Nugget", 75, 100, ["Ore", "Metal"], {description:"A nugget of platinum"}),
    //Jewelery
    "ring": new ItemTemplate("ring", "Ring", 50, 100, ["Jewelry"], {description:"A simple ring", canAugment:true}),
    "necklace": new ItemTemplate("necklace", "Necklace", 75, 100, ["Jewelry"], {description:"A simple necklace", canAugment:true}),
    "bracelet": new ItemTemplate("bracelet", "Bracelet", 50, 100, ["Jewelry"], {description:"A simple bracelet", canAugment:true}),
    //Food
    "apple": new ItemTemplate("apple", "Apple", 5, 100, ["Food", "Fruit"], {description:"A generic apple"}),
    "pear": new ItemTemplate("pear", "Pear", 7, 100, ["Food", "Fruit"], {description:"A generic pear"}),
    "orange": new ItemTemplate("orange", "Orange", 5, 100, ["Food", "Fruit"], {description:"A generic orange"}),
    "grape_bunch": new ItemTemplate("grape_bunch", "Grape Bunch", 7, 100, ["Food", "Fruit"], {description:"A bunch of grapes"}),
    "banana": new ItemTemplate("banana", "Banana", 7, 100, ["Food", "Fruit"], {description:"A generic banana"}),
    "plum": new ItemTemplate("plum", "Plum", 7, 100, ["Food", "Fruit"], {description:"A generic plum"}),
    "peach": new ItemTemplate("peach", "Peach", 7  , 100, ["Food", "Fruit"], {description:"A generic peach"}),
    "cherry": new ItemTemplate("cherry", "Cherry", 2, 100, ["Food", "Fruit"], {description:"A generic cherry"}),
    "strawberry": new ItemTemplate("strawberry", "Strawberry", 3  , 100, ["Food", "Fruit"], {description:"A generic strawberry"}),
    "blueberry": new ItemTemplate("blueberry", "Blueberry", 2  , 100, ["Food", "Fruit"], {description:"A generic blueberry"}),
    "elderberry": new ItemTemplate("elderberry", "Elderberry", 5  , 100, ["Food", "Fruit"], {description:"A generic elderberry"}),
    "cranberry": new ItemTemplate("cranberry", "Cherry", 3  , 100, ["Food", "Fruit"], {description:"A generic cranberry"}),
    
    //Easter Eggs
    "weasel_doll": new ItemTemplate("weasel_doll", "Weasel Doll", 1000, 1, ["Easter Egg", "Trinket", "Ultra Rare", "Weird"], {description:"Some might even say it's a bit gaudy."}),
    "wise_llama": new ItemTemplate("wise_llama", "Wise Llama", 690, 1, ["Easter Egg", "Trinket", "Ultra Rare", "Weird"], {description: "For some reason this reminds you of someone. It's oddly smug."}),
    "buzzed_bee": new ItemTemplate("buzzed_bee", "Buzzed Bee", 420, 1, ["Easter Egg", "Trinket", "Ultra Rare", "Weird", "Junk"], {description:"Somehow an even more clumsy form of a bee."}),
 };